import os

from src.onion_crypto import (
    FRAME_SIZE,
    NONCE_SIZE,
    HEADER_SIZE,
    PAYLOAD_SIZE,
    E2E_PLAINTEXT_SIZE,
    E2E_BLOCK_SIZE,
    E2E_SESSION_NOISE,
    Opcode,
)

DIRECTORY_URL      = os.getenv("DIRECTORY_URL", "http://127.0.0.1:5001")
RELAY_DELAY_MIN    = 0.5
RELAY_DELAY_MAX    = 2.0

HANDSHAKE_TIMEOUT  = 30
MAX_RETRIES        = 3
FILE_BATCH_TIMEOUT = 120
BATCH_SIZE         = 50
CHUNK_SIZE         = 3563
FLUSH_INTERVAL     = 8

LEASE_TTL          = 30

STATE_IDLE             = "IDLE"
STATE_AWAITING_CIRCUIT = "AWAITING_CIRCUIT"
STATE_AWAITING_ACK     = "AWAITING_ACK"
STATE_SESSION_ACTIVE   = "SESSION_ACTIVE"
STATE_SYN_RECEIVED     = "SYN_RECEIVED"

MODE_HANDSHAKE = "HANDSHAKE"
MODE_SESSION   = "SESSION"
